#!/bin/bash
# Recursively watch the Maestro backend source tree and restart the dashboard
# service whenever it changes. systemd .path units only watch a single
# path/directory (non-recursive), which is why the config/frontend watcher
# (maestro-dashboard.path) cannot cover this — a change anywhere under
# src/maestro/ (e.g. orchestration, config, execution, monitoring) is on the
# dashboard's import path and is otherwise only picked up on manual restart.
set -euo pipefail

WATCH_DIR="/home/symphony/maestro/src/maestro"
DEBOUNCE_SECONDS=3
# __pycache__/*.pyc churn is generated BY the dashboard process itself as it
# imports modules; without this exclude the watcher would restart itself in a
# loop every time the dashboard starts up and re-imports its own code.
EXCLUDE='(__pycache__|\.pyc$|/dashboard/web/)'

echo "watching $WATCH_DIR for backend source changes (excluding: $EXCLUDE)"

while true; do
  inotifywait -r -e modify,close_write,create,delete,move \
    --exclude "$EXCLUDE" "$WATCH_DIR" >/dev/null 2>&1

  # Debounce: keep draining events until a quiet period is reached, so a
  # multi-file save/checkout triggers one restart instead of several.
  while inotifywait -r -e modify,close_write,create,delete,move \
    -t "$DEBOUNCE_SECONDS" --exclude "$EXCLUDE" "$WATCH_DIR" >/dev/null 2>&1; do
    :
  done

  echo "backend source changed under $WATCH_DIR; restarting maestro-dashboard.service"
  systemctl restart maestro-dashboard.service
done
